### ISSUE TITLE
Inserting HTML markup into the email body

### ISSUE THREAD

**Issue by c9482** [zxjon22/VelocityMail#3]
Hello,

I insert text with html markup into the email body but the markup is not rendered properly (it's shown exactly how it's stored in the database). I tried decoding the text before putting it into the Velocity context to no avail. Many thanks in advance for a hint on how to achieve this. 

![image](https://user-images.githubusercontent.com/17013052/80886669-8351c500-8c83-11ea-8fde-909675ff974f.png)

**Comment by zxjon22** [comment]
[`VelocityMailOptions`](https://github.com/zxjon22/VelocityMail/blob/master/src/VelocityMail/Service/VelocityMailOptions.cs) has a property to turn this on or off. It's on by default for safety:

```c#
        /// <summary>
        /// Whether or not text inserted into the HTML body of a generated e-mail
        /// should be HTML-encoded. Text bodies are unaffected. Defaults to true.
        /// </summary>
        public bool? HtmlEncodeBody { get; set; }
```

You can set it in `Web.config` if you need disable it permanently for your app.

**Comment by c9482** [comment]
Got it, thanks!
